<a href="https://colab.research.google.com/github/GustaveRw/NLP-Fellowship/blob/master/NN_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import loadtxt
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
#Load the dtaset using pandas
import pandas as pd


df = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv')
df.to_csv('pima.csv')

#Use one of this
import requests

response = requests.get('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv')

with open('pima_r.csv', 'w+') as file:
  file.write(response.text)

In [ ]:
#load the data( .csv=',' & .tsv='\t')
dataset = loadtxt('/content/pima_r.csv', delimiter=',')
#split
x = dataset[:,0:8]
y = dataset[:,8]

#######

In [ ]:
df_x = np.array(df.iloc[:,0:8].astype(int))
df_y = np.array(df.iloc[:,8].astype(int))

In [ ]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
df_x

array([[  1,  85,  66, ...,  26,   0,  31],
       [  8, 183,  64, ...,  23,   0,  32],
       [  1,  89,  66, ...,  28,   0,  21],
       ...,
       [  5, 121,  72, ...,  26,   0,  30],
       [  1, 126,  60, ...,  30,   0,  47],
       [  1,  93,  70, ...,  30,   0,  23]])

In [ ]:
x[0]

array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
        50.   ])

In [ ]:
#Dfine the keras model
model = Sequential()
model.add(Dense(12, input_shape=(8,),activation='relu')) #Input Layers
#hidden Layers
model.add(Dense(8, activation='relu'))
model.add(Dense(6, activation='relu'))
#End of hidden layer
model.add(Dense(1, activation='sigmoid')) #Output layer

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(x, y, epochs=150, batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 2ms/step - loss: 11.4017 - accuracy: 0.5990
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 1.1222 - accuracy: 0.5443
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7596 - accuracy: 0.6237
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7166 - accuracy: 0.6263
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7094 - accuracy: 0.6576
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6469 - accuracy: 0.6771
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6396 - accuracy: 0.6654
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6778 - accuracy: 0.6602
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6205 - accuracy: 0.6862
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6259 - accuracy: 0.6810
Epoch 11

In [ ]:
_, accuracy = model.evaluate(x, y)
print(accuracy)

24/24 [==============================] - 0s 1ms/step - loss: 0.4382 - accuracy: 0.7943
0.7942708134651184
