<a href="https://colab.research.google.com/github/GustaveRw/NLP-Fellowship/blob/master/Text_To_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text to features
This is the process of converting tokens to numbers. This is because the machine only works with numbers. Moreover, for manipulation of text, the tokens need to be in digit form to apply any transformations.

The input of the function will be the matrix of tokens and output will be matrix with digits.

## Simplest form of featurization
The simplest way is to assign each unique text a number starting from 0 and increase by one until all the text has been assigned numbers

In [ ]:
import numpy as np

In [ ]:
# fitting


list_sentences = ['this is a list of sentences example', 'second sentence in list of sentence', 'a word for complexity',]
all_word = set()
word_to_index = {}
index_to_word = {}

for sent in list_sentences:
    #split the sentence into words
    for word in sent.split():
        # add the words to the set
        
        all_word.add(word)
    
    for index,word in enumerate(all_word):
        word_to_index[word] = index
        index_to_word[index] = word

word_to_index
print(word_to_index)

{'of': 0, 'a': 1, 'example': 2, 'is': 4, 'this': 6, 'sentences': 7, 'list': 10, 'second': 8, 'sentence': 9, 'in': 11, 'word': 3, 'complexity': 5, 'for': 12}


## Bag Of Words (BoW)
* Split the sentences into words
* Create a dictionary with all unique words and their indices
* Create a vector, size same as the total number of unique words
* For every word in a sentence, get the index and add 1. 
* The result will be a vector for each sentence with length same as all the unique words in all sentences, with frequency of each word in one particular sentence. If a word is not in that sentence, the frequency is 0


In [ ]:
transformed_list_words = np.zeros(len(all_word))
transformed_list_words

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Create a vector, size same as the total number of unique words

transformed_list_sentences = np.empty((len(list_sentences),len(all_word)))
transformed_list_sentences

array([[1.71251374e-316, 2.33419537e-312, 8.48798317e-313,
        2.22809558e-312, 2.46151512e-312, 2.44029516e-312,
        2.41907520e-312, 2.14321575e-312, 8.48798317e-313,
        2.35541533e-312, 2.12199579e-312],
       [2.46151512e-312, 2.01589600e-312, 2.33419537e-312,
        2.14321575e-312, 9.76118064e-313, 2.46151512e-312,
        2.31297541e-312, 8.48798317e-313, 9.33678148e-313,
        2.27053550e-312, 2.56761491e-312],
       [2.29175545e-312, 2.31297541e-312, 2.12199579e-312,
        6.79038654e-313, 2.46151512e-312, 2.31297541e-312,
        6.79038653e-313, 2.46151512e-312, 2.31297541e-312,
        1.03977794e-312, 8.70018275e-313]])

In [ ]:
for row,sentence in enumerate(list_sentences):
    #replace row with sentence BoW
    
    
    transformed_list_words = np.zeros(len(all_word))
    for word in sentence.split():
        if word in all_word:
            #get the index of the word
            word_index = word_to_index[word]
            #increase the value by 1
            transformed_list_words[word_index]+=1
            #print(transformed_list_words)

    transformed_list_sentences[row] =  transformed_list_words

print(dict(sorted(word_to_index.items(), key=lambda item: item[1])))
transformed_list_sentences


{'of': 0, 'a': 1, 'word': 2, 'complexity': 3, 'is': 4, 'this': 5, 'sentences': 6, 'second': 7, 'list': 8, 'in': 9, 'for': 10}


array([[1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 2., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
test_sentence = 'this is an example of sentence with sentence that are complexity with many example'
transformed_list_words = np.zeros(len(all_word))
for word in test_sentence.split():
    if word in all_word:
        #get the index of the word
        word_index = word_to_index[word]
        #increase the value by 1
        transformed_list_words[word_index]+=1
        #print(transformed_list_words)
transformed_list_words

array([1., 0., 2., 0., 1., 1., 1., 0., 0., 2., 0., 0., 0.])

## In-class Practicals

Convert this into a class and functions:


In [ ]:
class Bow:
    def __init__(self):
        # Enter code here


    def fit(self,document):
        
        #Enter code 
        

    def transform(self,data):
        
        #Enter code 
        return transformed

    def fit_transform(self,data):
        self.fit(data)

        return self.transform(data)

    def _transform_single(self,list_words):

       # This code is for transforming a single sentence

        return transformed

## Assignment
BOW using your tokens and share some sentences to text